// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiw56M7Zelwg7LPYESw2nVz9qq_XevSVM',
    appId: '1:892656577712:web:a2c04c8abf2c8cf3b39f75',
    messagingSenderId: '892656577712',
    projectId: 'scolage-9b666',
    authDomain: 'scolage-9b666.firebaseapp.com',
    storageBucket: 'scolage-9b666.firebasestorage.app',
    measurementId: 'G-YXC775WYDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWfTYfmTZJ0jlCGUfvXwvYY8gCBOOKD4',
    appId: '1:892656577712:android:566f3e77e5da9df5b39f75',
    messagingSenderId: '892656577712',
    projectId: 'scolage-9b666',
    storageBucket: 'scolage-9b666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1likKEdjlFUcdeZPAmVY5cRIS1IQWyJg',
    appId: '1:892656577712:ios:9a1b27ff2e3d3219b39f75',
    messagingSenderId: '892656577712',
    projectId: 'scolage-9b666',
    storageBucket: 'scolage-9b666.firebasestorage.app',
    iosBundleId: 'com.example.scolage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1likKEdjlFUcdeZPAmVY5cRIS1IQWyJg',
    appId: '1:892656577712:ios:9a1b27ff2e3d3219b39f75',
    messagingSenderId: '892656577712',
    projectId: 'scolage-9b666',
    storageBucket: 'scolage-9b666.firebasestorage.app',
    iosBundleId: 'com.example.scolage',
  );

}