// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxAxfCQSwo78fD-OsKCymhxzRPMw2fl0',
    appId: '1:64953881087:android:c6ebfbab9c6d31aef317ca',
    messagingSenderId: '64953881087',
    projectId: 'new-scolage',
    storageBucket: 'new-scolage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8LCuMFfwL2mAL_2Zequo-RNa0yL_w2Kw',
    appId: '1:64953881087:ios:3ac2b56ae451743ef317ca',
    messagingSenderId: '64953881087',
    projectId: 'new-scolage',
    storageBucket: 'new-scolage.firebasestorage.app',
    iosBundleId: 'com.catchcollage.name',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcyMhtrTCfXouBUGS7lyCaqr5a_EtEJDY',
    appId: '1:64953881087:web:1b0f577b5480e24cf317ca',
    messagingSenderId: '64953881087',
    projectId: 'new-scolage',
    authDomain: 'new-scolage.firebaseapp.com',
    storageBucket: 'new-scolage.firebasestorage.app',
    measurementId: 'G-84BRCLEL9V',
  );

}