// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiw56M7Zelwg7LPYESw2nVz9qq_XevSVM',
    appId: '1:892656577712:web:a2c04c8abf2c8cf3b39f75',
    messagingSenderId: '892656577712',
    projectId: 'scolage-9b666',
    authDomain: 'scolage-9b666.firebaseapp.com',
    storageBucket: 'scolage-9b666.firebasestorage.app',
    measurementId: 'G-YXC775WYDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeqTmBBRP_9nGM23feopHvJGxbp4lXHU',
    appId: '1:863032108599:android:b5a0016574ed8c309581b2',
    messagingSenderId: '863032108599',
    projectId: 'scollage-a7a19',
    storageBucket: 'scollage-a7a19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2kiZ5rqFca6-pkEajZwPbJSciScYanZI',
    appId: '1:863032108599:ios:8628d8e6860d00739581b2',
    messagingSenderId: '863032108599',
    projectId: 'scollage-a7a19',
    storageBucket: 'scollage-a7a19.firebasestorage.app',
    iosBundleId: 'com.example.newScolage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2kiZ5rqFca6-pkEajZwPbJSciScYanZI',
    appId: '1:863032108599:ios:8628d8e6860d00739581b2',
    messagingSenderId: '863032108599',
    projectId: 'scollage-a7a19',
    storageBucket: 'scollage-a7a19.firebasestorage.app',
    iosBundleId: 'com.example.newScolage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVkG4eCATe-mSdrIB_r8Z5ZIYdrwyPuA',
    appId: '1:863032108599:web:1aa14325b88f47c29581b2',
    messagingSenderId: '863032108599',
    projectId: 'scollage-a7a19',
    authDomain: 'scollage-a7a19.firebaseapp.com',
    storageBucket: 'scollage-a7a19.firebasestorage.app',
    measurementId: 'G-29FD537LX2',
  );

}